# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# send to fully-virtualized infrastructure: https://docs.travis-ci.com/user/reference/xenial/
sudo: required
dist: xenial

cache:
  # default timeout is too low
  timeout: 600
  directories:
  - $HOME/.m2
  - $HOME/flink_cache
  # keep in sync with tools/travis/setup_maven.sh
  - $HOME/maven_cache
  # keep in sync with tools/travis/docs.sh
  - $HOME/gem_cache
  - $HOME/flink_download_cache

# do not cache our own artifacts
before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/flink/

install: true

language: java

git:
  depth: 100

env:
  global:
    - cache-dir: $HOME/flink_download_cache
    - cache-btl: 30
    # Global variable to avoid hanging travis builds when downloading cache archives.
    - MALLOC_ARENA_MAX=2
    - DOCKER_COMPOSE_VERSION=1.22.0
    - CHANGE_MINIKUBE_NONE_USER=true

before_script:
   - "export -f travis_nanoseconds"
   - "export -f travis_time_start"
   - "export -f travis_time_finish"

# Install maven 3.2.5 since xenial uses 3.3.9 for which shading is broken
before_install:
   - source ./tools/travis/setup_maven.sh

stages:
  - name: compile
  - name: test
  - name: E2E
    if: type in (pull_request, push)
  - name: cleanup

jdk: "openjdk8"
jobs:
  include:
    # E2E profiles - Hadoop 2.8
    - if: type in (pull_request, push)
      stage: test
      env: PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -De2e-metrics -DincludeE2E=org.apache.flink.tests.util.categories.TravisGroup1"
      script: ./tools/travis/nightly.sh split_misc.sh
      name: e2e - misc - hadoop 2.8
    - if: type in (pull_request, push)
      env: PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -DincludeE2E=org.apache.flink.tests.util.categories.TravisGroup2"
      script: ./tools/travis/nightly.sh split_ha.sh
      name: e2e - ha - hadoop 2.8
    - if: type in (pull_request, push)
      env: PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -DincludeE2E=org.apache.flink.tests.util.categories.TravisGroup3"
      script: ./tools/travis/nightly.sh split_sticky.sh
      name: e2e - sticky - hadoop 2.8
    - if: type in (pull_request, push)
      env: PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -DincludeE2E=org.apache.flink.tests.util.categories.TravisGroup4"
      script: ./tools/travis/nightly.sh split_checkpoints.sh
      name: e2e - checkpoints - hadoop 2.8
    - if: type in (pull_request, push)
      env: PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -DincludeE2E=org.apache.flink.tests.util.categories.TravisGroup5"
      script: ./tools/travis/nightly.sh split_container.sh
      name: e2e - container - hadoop 2.8
    - if: type in (pull_request, push)
      env: PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -DincludeE2E=org.apache.flink.tests.util.categories.TravisGroup6"
      script: ./tools/travis/nightly.sh split_heavy.sh
      name: e2e - heavy - hadoop 2.8
    - if: type in (pull_request, push)
      env: PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -DincludeE2E=org.apache.flink.tests.util.categories.TravisGroup6"
      script: ./tools/travis/nightly.sh split_tpcds.sh
      name: e2e - tpcds - hadoop 2.8
